- name: variables to print
  hosts: web
  vars: 
    COURSE: "DevOps with Aws"
    DURATION: "120 hours"
    TRAINER: "DevOps Trainer"
  tasks:
  - name: print the information
    ansible.print.debug: # To print the information
      msg: "Hi, I am learning {{COURSE}, Duration is: {{DURATION}}, Tariner is: {{TRAINER}}"