- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the dufault information
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to upper
    vars:
      greeting: "Hello Ranjith"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"  


  - name: convert to lower
    vars: 
      greeting: "HELLO RANJITH" 
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"  

  - name: get the unique numbers
    vars:
      numbers: [1,2,3,4,5,5,4,3,2,1,100]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"   

  - name: get min and max number
    vars:
      number: [1,2,3,100]
    ansible.builtin.debug:
      msg: "Min: {{ number | min }} Max: {{ number | max }}"    

  - name: convert map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: "120 hours"
        trainer: "DevOps"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"         

  - name: convert list to map
    vars:
      course:
      - { "key": "name","value": "DevOps with AWS" }
      - { "key": "duration","value": 120 }
      - { "key": "trainer","value": "sivakumar reddy" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"

  - name: check ip address
    vars:
      myip: "192.168.1.1"
    ansible.builtin.debug:
      msg: " {{ myip | ansible.utils.ipv4 }}"  
