- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the dufault information
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to upper
    vars:
      greeting: "Hello Ranjith"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"  


  - name: convert to lower
    vars: 
      greeting: "HELLO RANJITH" 
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"  

  - name: get the unique numbers
    vars:
      numbers: [1,2,3,4,5,5,4,3,2,1,100]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"    