- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0f481d19b685aac95 # Replace with your subnet id
    sg_id: sg-0f575d808e73f7ee2
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: devops81s.site
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"  
    register: ec2_instances
      
  - name: print the information
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"    

  # private ip address
  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.devops81s.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true    
      overwrite: trueg
    loop: "{{ ec2_instances.results }}"  

  # public ip address
  - name: create r53 public records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #devops81s.site
      type: A
      ttl: 1
      value: "{{ item.instance[0].public_ip_address }}"
      wait: true    
      overwrite: true
    loop: "{{ ec2_instances.results }}"    
    when: item.item == "frontend"