- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0353fbc5b0a2e4017 # Replace with your subnet id
    sg_id: sg-015fed1b787f2227c
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: aws80s.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"  
    register: ec2_instances
      
  - name: print the information
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"    

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.aws80s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true    
      overwrite: true
    loop: "{{ ec2_instances.results }}"  